### ISSUE TITLE
Small getting started issue

### ISSUE THREAD

**Issue by kontur** [schriftgestalt/GlyphsSDK#10]
Two simple non-issues that kept be scratching my head when trying to figure out how to get started writing a plugin:
- Once you have located the plugins folder and copied a plugin template there, it took me some googling that in order to get the "bundle" I simply need to rename the folder to a `.glyphsReporter` or `.glyphsPlugin` 
- I was checking in the Plugin Manager on how to activate my new local development plugin, without realising that it simply _is_ activated

Outlining these two simple pitfalls in the "getting started" part would be helpful.

**Comment by mekkablue** [comment]
The plugin templates already have those name suffixes. I wonder why they didn't in your case and you had to rename them…?

**Comment by kontur** [comment]
Hm, true that. I cloned the GlyphsSDK repo, then copied the folder with the template I wanted to tinker with. Maybe the copy paste removes the extension? It may be worth mentioning in the intro either way, even if in most cases it stays intact.
