### ISSUE TITLE
Reporter not executed when Caret is at the end of a text

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/GlyphsSDK#11]
I noticed, that when you are in an Edit Tab and the Text Cursor aka Caret is at the very end, the reporter is not executing code. Is that on purpose? Could it be made to run? I know there could be an issue with the selectedLayer, but one could handle this in other ways (e.g. having a return `None` for that situation)

**Comment by yanone** [comment]
+1

**Comment by schriftgestalt** [comment]
this should be fixed now

**Comment by Mark2Mark** [comment]
I think it ain’t, unfortunately. Are you sure you are talking of the same issue? @schriftgestalt

**Comment by mekkablue** [comment]
To get this right: You mean it should at least execute for the `inactiveLayers` and it does not?

**Comment by Mark2Mark** [comment]
Not sure if this is what I mean.

When the caret is at the end of a line (so no active layer (kind of yes)) they are not running in that case. This disables all functionalities which are not drawing methods. Like user interfaces for example. If a UI is open and the user goes to the Font Tab, there’s no way to hide the UI, because I cannot get any notification (e.g. willDeactivate is not called there).

The Variable Font Preview plugin for instance also freezes in that case. In my newest objective-C  version I can at least keep the preview panel stay stuck to the edit view, but the content is still not updating unless one is not at the end of a line:

In Edit Tab, type:
`Hello*` (The * is where your Caret/InsertionPoint is)
Keep typing:
`Hello World*`
All the mentioned reporters, as well as Synced Tabs are not doing anything. But, if you type like this:
`Hell*o` (Note: Insertion point is *not* at the end)
`Hello World*o`
All reporters keep doing their job. That’s showing the expected behaviour.
