### ISSUE TITLE
BUG: node.selected = True

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/GlyphsSDK#12]
`node.selected = True` was once working. It isn’t anymore.
Can you please fix it? Or how can i set a node selected now?

```
File "GlyphsApp/__init__.py", line 3211, in <lambda>
File "GlyphsApp/__init__.py", line 2234, in SetObjectInLayer_selected
AttributeError: '__LayerSelectionProxy' object has no attribute 'append'
```

Many thanks in advance!

**Comment by schriftgestalt** [comment]
What version of Glyphs do you have? And do you happen do have an old version of `GlyphsApp.py` in your script folder?

**Comment by Mark2Mark** [comment]
I’m mostly using the latest (?) stable Version 2.4.2 (1060)

There’s no `GlyphsApp.py` in the scripts folder. Only the `objectsGS.py` and `GSPen.py` from you.

**Comment by schriftgestalt** [comment]
The latest stable is 1064.

**Comment by Mark2Mark** [comment]
Ah, thanks for the reminder! I can confirm, that it works in 1064 👍
