### ISSUE TITLE
drawingTools.drawGlyph(glyph)

### ISSUE THREAD

**Issue by jenskutilek** [schriftgestalt/GlyphsSDK#14]
https://github.com/schriftgestalt/GlyphsSDK/blob/master/ObjectWrapper/GlyphsApp/drawingTools.py#L8

-> AttributeError: 'NSKVONotifying_GSGlyph' object has no attribute '_layer'

**Comment by schriftgestalt** [comment]
can you send me a sample script?

**Comment by jenskutilek** [comment]
For example if you run this in the Skedge plugin:

```python
from GlyphsApp.drawingTools import *
g = Glyphs.font.glyphs[0]
drawGlyph(g)
```

I used it in a plugin other than Skedge, the same error occurs there, but I changed the plugin since to draw the paths of the layers directly using `drawPath(layer.bezierPath)`.

**Comment by Mark2Mark** [comment]
Hmm, this *could* have to do with the way code is executed within Skedge. I am not sure about what happens exactly, yet …

**Comment by schriftgestalt** [comment]
The drawGlyph() needs and RGlyph as an argument. If you don’t use robo stuff already, use the nativ API as you already do.
