### ISSUE TITLE
Typo in file format description (?)

### ISSUE THREAD

**Issue by delucis** [schriftgestalt/GlyphsSDK#15]
The [Glyphs File Format document](https://github.com/schriftgestalt/GlyphsSDK/blob/master/GlyphsFileFormat.md) lists `glyphs` ⇒ `layers` ⇒ `path`, but in my `.glyphs` files, it appears to be `paths` not `path`. Is that a typo or are both `paths` and `path` possible?

**Comment by schriftgestalt** [comment]
Fixed that and found some more. Thanks or the report
