### ISSUE TITLE
[format] Retain foreign data

### ISSUE THREAD

**Issue by davelab6** [schriftgestalt/GlyphsSDK#2]
#### Problem

I made an example file, saved it, copied it, edited it in a text editor to add some "foreign" data, and then opened and saved it as a 3rd file. That file lost my data. 

Files are here: https://gist.github.com/davelab6/c5fa105bcac695e83cae
#### Expected result

The 3rd file still has my data
#### Suggestion

Glyphs should retain arbitrary plist-conformant data in glyphs file

**Comment by schriftgestalt** [comment]
This is not supported (yet). I would like to avoid it as it poses some performance problems. And there is the userData dict that is intended to store custom data. the userData property is available at font, glyph, layer, node, fontMaster. I just saw that some of them are missing in the spec.

**Comment by davelab6** [comment]
The performance problems only effect data you don't anticipate though,
right? So if you enable this and allow users to opt in to tracking foreign
keys, you can build up a list/dictionary of anticipated keys/types?

**Comment by schriftgestalt** [comment]
The performance is mostly a problem when saving. I don’t use a library or intermediate representation to write the file. The keys should be in alphabetical order and so I have to check after each of my keys, if there is a custom key available...

**Comment by davelab6** [comment]
What if there was a key like alwaysRoundtripKeys (so,at the top) which only
when present triggered this check? :)
