### ISSUE TITLE
.glyphsPalette template: missing ‘self.dialogName’

### ISSUE THREAD

**Issue by mekkablue** [schriftgestalt/GlyphsSDK#24]
A .glyphsPalette built from the template, will write an error into the Macro window stating that self.dialogName was not set or missing. I can fix it by adding `self.dialogName = self.name` to the `settings()` method.

Is there a structural difference between `name` and `dialogName` or are they they same? And if so, should the line above be added to `plugins.py`?

**Comment by schriftgestalt** [comment]
das muss einfach `self.name` heißen. Ich repariere das.
