### ISSUE TITLE
.glyphsPalette template: missing method `currentHeight`

### ISSUE THREAD

**Issue by mekkablue** [schriftgestalt/GlyphsSDK#25]
A `.glyphsPalette` built from the template will miss the `currentHeight()` method, and hence produce a lot of error messages in the macro log.

Add `currentHeight` to the template? Or with some smart code to `plugins.py`?

**Comment by schriftgestalt** [comment]
The `currentHeight()` is implemented in `plugins.py`. That should be enough?

**Comment by mekkablue** [comment]
It can return `None`:

```python
	def currentHeight(self):
		"""
		The current height of the Palette section.
		Used for storing the current resized state.
		If you have a fixed height, you can also return the height in pixels
		"""
		try:
			# return 150
			return NSUserDefaults.standardUserDefaults().integerForKey_(self.dialogName + ".ViewHeight")
		except:
			self.logError(traceback.format_exc())
```

**Comment by schriftgestalt** [comment]
not if it is not throwing because of `self.dialogName`

**Comment by mekkablue** [comment]
Fair enough.
