### ISSUE TITLE
GSBackgroundlayer.foreground is a function, not a property

### ISSUE THREAD

**Issue by madig** [schriftgestalt/GlyphsSDK#31]
Is this intentional?

**Comment by schriftgestalt** [comment]
You mean when you call it in Glyphs? This is how the pyobjec bridge works. And most of the wrapper is there to "fix" that. And `GSBackgroundlayer.foreground` is not wrapped, yet.

**Comment by madig** [comment]
Ok :) Not really important, just found this discrepancy with glyphsLib.

**Comment by schriftgestalt** [comment]
If it is a property in glyphsLib, that is fine. I’ll add it to the wrapper.
