### ISSUE TITLE
GSFontMaster.stems / GSFontMaster.verticalStems

### ISSUE THREAD

**Issue by simoncozens** [schriftgestalt/GlyphsSDK#32]
The documentation says `verticalStems` (which was the attribute in Glyphs 2) but it looks like the new name is just `stems`? Either code or documentation is wrong...

**Comment by simoncozens** [comment]
.horizontalStems is broken too

```
    h = m.horizontalStems
  File "GlyphsApp/GlyphsApp/__init__.py", line 3694, in <lambda>
AttributeError: No selector horizontalStems
```

**Comment by schriftgestalt** [comment]
The docs are not touched, yet. I’m working on it. 

Form now, the header files in the framework are your best source. 

Yes, the stems are in one list now. If that happens do not make any sense at all, there is still time to change it. But it works for me, so far.

**Comment by simoncozens** [comment]
It's fine, I can do something like this:

```
hstems = [x.value() for x in filter(lambda x:x.metric().horizontal(), stems)]
vstems = [x.value() for x in filter(lambda x:not x.metric().horizontal(), stems)]
```
