### ISSUE TITLE
Executable in Python template causes notarization failure

### ISSUE THREAD

**Issue by takaakifuji** [schriftgestalt/GlyphsSDK#36]
Notarization fails when uploaded the custom plugin bundle based on the Python template in this repository, with the following message:

```
The binary uses an SDK older than the 10.9 SDK.
```
@mekkablue seems to be using the newer version of the Mach-O executable named `plugin`, which looks like a tiny helper that loads a PyObjC class from the path specified in `Info.plist`, and the notarization is successfully completed when uploading the bundle to Notary Service after replacing that binary with his version.

So, it looks to me that the Python templates in this repository are outdated somehow and need to be updated to be notarization ready. I'm afraid that's a bit confusing to users, and I would be more than happy if the copies of the executable in this repository would be in sync with the latest version you have. Also `main.py` could possibly be removed from the template if it's not needed anymore.

**Comment by schriftgestalt** [comment]
The plugins don't need notarisation any more - if you download a repo through git or install the plugin by "opening" it in Glyphs. 
Please try the templates form the Glyphs3 branch. It contains the same binaries that are in @mekkablue’s plugins.

**Comment by takaakifuji** [comment]
I've read the release notes for 2.6.5 and I'm really happy with how Glyphs does the magic for us. My understanding is that just moving a plugin bundle to `~/Application Support/Glyphs/Plugins` doens't work any more (unless notarised), and the users needs to make sure to open it with Finder to make the magic happen.

The template/example files in the Glyphs 3 branch are what I needed. It looks like those could be used for Glyphs 2 as well. Thanks for the information!
