### ISSUE TITLE
Remote scripts in G3

### ISSUE THREAD

**Issue by guidoferreyra** [schriftgestalt/GlyphsSDK#43]
Hi! Are [remote scripts](https://github.com/schriftgestalt/GlyphsSDK/tree/master/Glyphs%20remote%20scripts) working with Glyphs 3?

**Comment by schriftgestalt** [comment]
I think so.

**Comment by guidoferreyra** [comment]
Yes, sorry. I needed to update Glyphs.py, I thought I had.

Btw, before the code below worked for me, now I’m getting "AttributeError: 'NSDistantObject' object has no attribute 'familyName'"
```
doc = Glyphs.openDocumentWithContentsOfFile_display_(path, False)
font = doc.font()
print (font.familyName())
```

**Comment by schriftgestalt** [comment]
Thats because the internal API has changed. It is `font.fontName()`, now. You can check the headers for details.
