### ISSUE TITLE
NSRangeException with "currentTab", if you put the textCursor after the last glyph.

### ISSUE THREAD

**Issue by mumchristmas** [schriftgestalt/GlyphsSDK#47]
Here is the Traceback info.
> Traceback (most recent call last):
>   File "<macro panel>", line 3
>   File "_convenience_nsarray.py", line 138, in nsarray__getitem__
>     return container_unwrap(self.objectAtIndex_(idx), RuntimeError)
> IndexError: NSRangeException - *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray

![6831613912919_ pic](https://user-images.githubusercontent.com/126215/108626567-be7be980-748b-11eb-82db-67748f8eb10f.jpg)

![6881613913068_ pic_hd](https://user-images.githubusercontent.com/126215/108626576-c63b8e00-748b-11eb-908b-a6265390adf5.jpg)

**Comment by schriftgestalt** [comment]
are you sure that the error is from the line you show? the error messages says it is in line 3?

**Comment by mumchristmas** [comment]
> are you sure that the error is from the line you show? the error messages says it is in line 3?

oh my, that's true. Just missed the # on it... 
"layer = Glyphs.font.selectedLayers[0]" witch I always leave it there
