### ISSUE TITLE
`GSGuide.filter` should not be a `bool` value

### ISSUE THREAD

**Issue by stone-zeng** [schriftgestalt/GlyphsSDK#55]
`GSGuide.filter` should not be a `bool` value:

https://github.com/schriftgestalt/GlyphsSDK/blob/0aa2bfddc01b2112987fa81d3dd777fd0a68186b/ObjectWrapper/GlyphsApp/__init__.py#L9993-L10000

In Glyphs, there is the same issue:

```py
guide = Font.masters[0].guides[0]

print(guide)
print(guide.filter)
print(guide.pyobjc_instanceMethods.filter())
```

Output:

```
<GSGuide x=257.0 y=355.0 angle=0.0>
True
tags CONTAINS "guide_Test"
```

**Comment by schriftgestalt** [comment]
Right. Thanks.
