### ISSUE TITLE
Can’t access `self.windowController()` from GeneralPlugin (Python)

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/GlyphsSDK#63]
In a GeneralPlugin (created from the Plugin Maker) I can’t access the windowController as the sample "Smiley Palette" shows.

`self.windowController(): object has no attribute 'windowController'`

Other Plugins (by mekkablue also use it, but they are of a different type. Is that an issue with the GeneralPlugin type? And how to solve it?

**Comment by schriftgestalt** [comment]
GeneralPlugin has no windowcontroller. The panel plugin does have it (as there is an instance of the plugin per window). The GeneralPlugin needs to get to the windows by `[NSApp mainWindow]`, `[NSApp currentFontDocument];` or `[NSApp orderedDocuments]`.

**Comment by Mark2Mark** [comment]
Thanks a lot!
Will also add this to the Sample Plugin as a comment.
