### ISSUE TITLE
previewInstances = 'live' not showing the live preview

### ISSUE THREAD

**Issue by weiweihuanghuang** [schriftgestalt/GlyphsSDK#7]
`Glyphs.font.currentTab.previewInstances = 'live'`
Doesn't give me the live preview but the following does:
`# thisTab.previewInstances = Font.instances[-1]`

**Comment by schriftgestalt** [comment]
What version of Glyphs do you have. That is available on 2.3 837 or 838.

**Comment by weiweihuanghuang** [comment]
I'm on 837, `Glyphs.font.currentTab.previewInstances = 'live'` shows me the first instance.

**Comment by weiweihuanghuang** [comment]
Even running 

```currentPreviewInstance = thisTab.previewInstances

print currentPreviewInstance```

shows the wrong output.

**Comment by schriftgestalt** [comment]
I think it the popup is not properly updated. The preview uses the correct setting. I’ll fix it.

**Comment by yanone** [comment]
This feature doesn't even show in the documentation yet. Where did you learn about it?
Anyway, we’ve changed the implementation for this in 838, as Georg said. Updating Glyphs should help.

**Comment by weiweihuanghuang** [comment]
@yanone i snuck around in the GlyphsApp.py :D

**Comment by yanone** [comment]
Like a good developer should
