### ISSUE TITLE
Documentation: `GSAxis` > `axisId` wrongly attributed as `id`

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/GlyphsSDK#71]
In the properties table of content it’s called correctly `axisId` but below in the explanaition it is just called `id`

Hence also the hyperlink doesn’t work.

<img width="723" alt="Screenshot 2022-08-11 at 20 01 17" src="https://user-images.githubusercontent.com/5824595/184208069-9e4d9f71-d92d-4d5b-8112-b266987411d8.png">

**Comment by Mark2Mark** [comment]
@schriftgestalt 
- [ ] It still looks like in the image above. Why is it closed?
- [ ] should `axisId` be readonly? Asking for the unit test and documentation.

**Comment by schriftgestalt** [comment]
>  It still looks like in the image above. Why is it closed?
I changed it in the original source but didn't upload the new docu, yet. This is a bit more complicated.

> should axisId be readonly? Asking for the unit test and documentation.

probably not readonly.
