### ISSUE TITLE
delete path with `del(Layer.paths[0])` not supported

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/GlyphsSDK#74]
`>>> TypeError: 'GSProxyShapes' object doesn't support item deletion`

The documentation [claims that it is possible](https://docu.glyphsapp.com/#GSLayer.paths) like that.

Also: what’s the proper API now to delete/add paths?

**Comment by schriftgestalt** [comment]
del(Layer.shapes[0])

**Comment by Mark2Mark** [comment]
Thanks!

Is there an easy way to distinguish between paths and components?
When a user wants to only delete either or.
I know one could type check as on objc, but for the regular python user? It’s not all too clear with the `.shapes` I think.

**Comment by florianpircher** [comment]
You can use [`shapeType`](https://docu.glyphsapp.com/#gsshape).

**Comment by Mark2Mark** [comment]
Thanks!

Should anyone add that to the Documentation?

**Comment by florianpircher** [comment]
I linked to the documentation. Or what other documentation do you use?

**Comment by Mark2Mark** [comment]
Didn’t see that it is a link. I also linked mine, though (twice 😉 )
Tried to point y’all to the part under GSLayer > paths, where it says:

```py
# access all paths
for path in layer.paths:
print(path)
# delete path
del(layer.paths[0]) # <------------- this is what I am talking about.
# copy paths from another layer
import copy
layer.paths = copy.copy(anotherlayer.paths)
```

**Comment by florianpircher** [comment]
Yes, that part is wrong.

**Comment by schriftgestalt** [comment]
The docu is generated from the comments in the wrapper file. It uses a script to extract the comments and then uses sphinx to build the html. https://github.com/schriftgestalt/GlyphsSDK/tree/Glyphs3/ObjectWrapper/Sphinx%20Documentation

**Comment by schriftgestalt** [comment]
The formatting is a bit tricky (indentation and empty lines). I can clean it up if needed.
