### ISSUE TITLE
How to draw only when editing and not in text cursor mode

### ISSUE THREAD

**Issue by weiweihuanghuang** [schriftgestalt/GlyphsSDK#8]
I.e. only here:
![screen shot 2016-03-22 at 10 43 08 am](https://cloud.githubusercontent.com/assets/1271897/13947445/ee4103b2-f01a-11e5-83d1-2c9a6aa12b6c.png)

and not here:
![screen shot 2016-03-22 at 10 43 10 am](https://cloud.githubusercontent.com/assets/1271897/13947447/f1381c2c-f01a-11e5-8634-c08c6d00af60.png)

**Comment by schriftgestalt** [comment]
How do you draw? Reporter plugin? What method is your drawing code in?

**Comment by weiweihuanghuang** [comment]
Trying to change this plugin, here's the method:

https://github.com/Mark2Mark/Show-Smart-Plumblines/blob/master/SmartPlumblines.glyphsReporter/Contents/Resources/SmartPlumblines.py#L132

**Comment by mekkablue** [comment]
You can check for the active tool.

```
currentController = self.controller.view().window().windowController()
if currentController:
	tool = currentController.toolDrawDelegate()
	if not tool.isKindOfClass_( NSClassFromString("GlyphsToolText") ):
		...
```

**Comment by weiweihuanghuang** [comment]
Thanks! And how can you check also if spacebar preview is active?

**Comment by Mark2Mark** [comment]
Just curious: What are you going to change? Appart from this particular request, did you spot any issues?
BTW: There is a little problem with the Italic Angle sometimes, couldn’t figure out the math properly, breaks my head.

**Comment by weiweihuanghuang** [comment]
@Mark2Mark no issues! I just changed the plugin so that it only shows

- Horizontal line from left of screen to right of screen, 
- Vertical line from bottom of glyph bounds to top,

And only active while editing and not while previewing with text tool or spacebar preview

**Comment by mekkablue** [comment]
Take a look at this snippet for your italic math:
```
import math
def italicize( thisPoint, italicAngle=0.0, pivotalY=0.0 ):
	"""
	Returns the italicized position of an NSPoint 'thisPoint'
	for a given angle 'italicAngle' and the pivotal height 'pivotalY',
	around which the italic slanting is executed, usually half x-height.
	Usage: myPoint = italicize(myPoint,10,xHeight*0.5)
	"""
	x = thisPoint.x
	yOffset = thisPoint.y - pivotalY # calculate vertical offset
	italicAngle = math.radians( italicAngle ) # convert to radians
	tangens = math.tan( italicAngle ) # math.tan needs radians
	horizontalDeviance = tangens * yOffset # vertical distance from pivotal point
	x += horizontalDeviance # x of point that is yOffset from pivotal point
	return NSPoint( x, thisPoint.y )
```

**Comment by Mark2Mark** [comment]
@mekkablue Thank you!
I think I already got parts of this in there. I am trying to get an italizised boundingBox (for reasons I cannot remember right now) in that particular plugin. But I cannot even recreate the problem I had. Will keep an eye on it.

**Comment by weiweihuanghuang** [comment]
bump also for:
Checking also if spacebar preview is active?

**Comment by weiweihuanghuang** [comment]
@schriftgestalt @mekkablue how to checking also if spacebar preview is active?

**Comment by schriftgestalt** [comment]
Can you try `Glyphs.spaceDown()`

**Comment by weiweihuanghuang** [comment]
Not working, 

```
if currentController:
				tool = currentController.toolDrawDelegate()
				if tool.isKindOfClass_( NSClassFromString("GlyphsToolSelect") ) and Glyphs.spaceDown() == 0:
```

**Comment by schriftgestalt** [comment]
Can you send me the whole thing?
