### ISSUE TITLE
GSFilterPlugin: template misses `[super setup]` call

### ISSUE THREAD

**Issue by takaakifuji** [schriftgestalt/GlyphsSDK#82]
https://github.com/schriftgestalt/GlyphsSDK/blob/27cc016629b148be160f01aae1227abbea1c35b9/Xcode%20Templates/Glyphs%20Dev/Glyphs%20Filter%20Plugin.xctemplate/___PACKAGENAMEASIDENTIFIER___.m#L55-L56

Needs to insert

```objc
[super setup];
```

here, otherwise we end up having `nil` in `_shadowLayers` at `- process:` and the filter won't work as the container will never be initialized.

**Comment by schriftgestalt** [comment]
fixed in d23a209e92bea5625c7a3d8d975540621bd0b932
