### ISSUE TITLE
align="topleft" seem to not work with self.drawTextAtPoint()

### ISSUE THREAD

**Issue by HugoJourdan** [schriftgestalt/GlyphsSDK#83]
I don't know if the right place to report this issue but when using this in Report Plugin :
```python
self.drawTextAtPoint("Hello1\nHello1\nHello2", NSPoint(200, 300), align="topleft")
```
`topright` and `topcenter` works, only `topleft` don't work.

**Comment by schriftgestalt** [comment]
Do you have some code where that is sued? It is easier to debug if I don’t need to recreate everything.

**Comment by HugoJourdan** [comment]
Yes of course : 

[____PluginName____.glyphsReporter.zip](https://github.com/schriftgestalt/GlyphsSDK/files/10834281/____PluginName____.glyphsReporter.zip)

**Comment by schriftgestalt** [comment]
There are two things that cause this. 
1) you use a scaled string drawing method in a unscaled drawing callback. You probably have realized that the text scaled strangely when you zoom. 
2) You use more than one line of text. For "topleft" there is a small optimization that expects only one line and a certain font size.

I’ll cleaned the code up a bit. Should work now.

To avoid the scaling of the test, use this:
```
	font = Glyphs.font
	tab = font.currentTab
	viewPort = tab.viewPort;
	x = viewPort.origin.x + 10
	y = viewPort.origin.y + viewPort.size.height - 10
	font_size = 10.0 * tab.scale
	self.drawTextAtPoint("Hello1\nHello1\nHello2", NSPoint(x, y), fontSize=font_size, align="topleft")
```
