### ISSUE TITLE
How was the. xib file created and in what language was it written.

### ISSUE THREAD

**Issue by jingmingtao** [schriftgestalt/GlyphsSDK#86]
How was the. xib file created and in what language was it written. How can I create my own. xib file if the template I need is different from the one provided by the official

**Comment by schriftgestalt** [comment]
I answered it in the forum: https://forum.glyphsapp.com/t/may-i-ask-a-question-about-plugin-writing-objective-c-language-is-only-used-to-generate-xib-files-if-my-plugin-does-not-require-dialog-functionality-i-do-not-need-to-use-objective-c-language-right/25919/3
