### ISSUE TITLE
Do I need to use object-c language to write practical Python templates for glyphs? Can I just use Python language to create plugins

### ISSUE THREAD

**Issue by jingmingtao** [schriftgestalt/GlyphsSDK#87]
Do I need to use object-c language to write practical Python templates for glyphs? Can I just use Python language to create plugins

**Comment by schriftgestalt** [comment]
I answered it in the forum: https://forum.glyphsapp.com/t/may-i-ask-a-question-about-plugin-writing-objective-c-language-is-only-used-to-generate-xib-files-if-my-plugin-does-not-require-dialog-functionality-i-do-not-need-to-use-objective-c-language-right/25919/3
