### ISSUE TITLE
Compiler xib exécuter ibtool xxx.xib - - compile xxx.nib erreur de Times:

### ISSUE THREAD

**Issue by jingmingtao** [schriftgestalt/GlyphsSDK#88]
Compiler xib exécuter ibtool xxx.xib - - compile xxx.nib erreur de Times:
xcode-select: error: tool 'ibtool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by schriftgestalt** [comment]
Answered in the forum: https://forum.glyphsapp.com/t/compiler-xib-executer-ibtool-xxx-xib-compile-xxx-nib-erreur-de-times/25920/3
