### ISSUE TITLE
Wrong export name in `GlyphPreview.py`

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/GlyphsSDK#90]
1.
I think that should be `GlyphPreview` instead of `GlyphView`:

https://github.com/schriftgestalt/GlyphsSDK/blob/8d3fcc8b0144dd75b00256a49cd7492d56be2ee8/ObjectWrapper/GlyphsApp/UI/GlyphPreview.py#L5

---

2.
Also maybe add some documentation of how to import it properly.

I could not make it work neither of these imports `from GlyphsApp import *` or `from GlyphsApp.plugins import *`, so I just added the entire `GlyphPreview.py` to my plugin and import that one.

The `from objectsGS import GlyphPreview` from the file’s sample code does not work.

**Comment by schriftgestalt** [comment]
This is fixed and there is some sample code.
