### ISSUE TITLE
GSAnchor doesn't accept arguments when creating an instance via Python

### ISSUE THREAD

**Issue by takaakifuji** [schriftgestalt/GlyphsSDK#94]
```python
anchor = GSAnchor('top', NSPoint(100, 100))
```

The code above fails with the error `TypeError: GSAnchor() does not accept positional arguments`. Looks like the line

```python
GSAnchor.__new__ = staticmethod(GSObject__new__)
```

has been somehow missing in the G3 wrapper.

```
$ diff -u <(curl -sL 'https://raw.githubusercontent.com/schriftgestalt/GlyphsSDK/refs/heads/master/ObjectWrapper/GlyphsApp/__init__.py' | grep '\.__init__' | cut -d' ' -f1 | sort | sed 's/\.__init__//g') <(curl -sL 'https://raw.githubusercontent.com/schriftgestalt/GlyphsSDK/refs/heads/master/ObjectWrapper/GlyphsApp/__init__.py' | grep '\.__new__' | cut -d' ' -f1 | sort | sed 's/\.__new__//g') | grep '^-GS'
```

```diff
-GSAnchor
-GSBackgroundImage
-GSComponent
-GSGuideLine
-GSNode
```

Just in case the classes listed above might need the same fix. I hope you could look into this when you have time.

**Comment by schriftgestalt** [comment]
I was testing in python 3.11 and it works there. But from Python 3.12 it doesn’t. I’ll fix it.

**Comment by takaakifuji** [comment]
Thanks for your response! I realised I was using the latest pyobjc==10.3.1. I think it works okay if I downgrade it to 10.0.0, which is the version that comes with GlyphPythonPlugin.

> https://pyobjc.readthedocs.io/en/latest/changelog.html#version-10-3
> Instantiating an Objective-C class by calling the class (e.g. invoking __new__) will not call __init__ even if one is defined

PyObjC 10.3 seems to have a breaking change.

**Comment by schriftgestalt** [comment]
works in python3.13 and pyobic 10.3.2 not.
